# Generated by Django 5.1 on 2024-08-17 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_time", models.DateTimeField(verbose_name="date_published")),
                ("content", models.CharField(max_length=1000)),
                ("title", models.CharField(max_length=200)),
                ("src", models.CharField(max_length=10)),
                ("industry_tag", models.CharField(max_length=10)),
                ("ele_tag", models.CharField(max_length=10)),
            ],
        ),
    ]
