# Generated by Django 4.0.1 on 2024-08-25 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='news',
            table='News',
        ),
    ]
