# Generated by Django 4.0.1 on 2024-08-28 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='keywords',
            field=models.CharField(default='', max_length=100),
        ),
    ]
